### ISSUE TITLE
EGM is inactive! Refusing to start controller

### ISSUE THREAD

**Issue by robberthofmanfm** [ros-industrial/abb_robot_driver#13]
I have an ABB YuMi with State Machine 1.1 installed.
I am trying to reproduce [Example 3 from the abb_robot_bringup_examples](https://github.com/ros-industrial/abb_robot_driver/tree/master/abb_robot_bringup_examples#example-3-ex3_rws_and_egm_yumi_robot).

When running the first `roslaunch` command, at first I think everything executes properly, and the right nodes are started (I left out the parameters here):
```
NODES
  /yumi/
    egm_controller_stopper (abb_egm_hardware_interface/egm_controller_stopper)
    egm_hardware_interface (abb_egm_hardware_interface/egm_hardware_interface)
    rws_service_provider (abb_rws_service_provider/rws_service_provider)
    rws_state_publisher (abb_rws_state_publisher/rws_state_publisher)
  /yumi/egm/
    started (controller_manager/spawner)
    stopped (controller_manager/spawner)

auto-starting new master
process[master]: started with pid [161065]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e7d5d8ee-6d5c-11eb-84ab-6d5730e35275
process[rosout-1]: started with pid [161075]
started core service [/rosout]
process[yumi/rws_state_publisher-2]: started with pid [161082]
process[yumi/rws_service_provider-3]: started with pid [161083]
process[yumi/egm_hardware_interface-4]: started with pid [161084]
process[yumi/egm_controller_stopper-5]: started with pid [161089]
process[yumi/egm/started-6]: started with pid [161092]
process[yumi/egm/stopped-7]: started with pid [161098]
```
However, it does give me 14 warnings for each of the joints soft limits.
`[ WARN] [1613153137.292019857]: Configured default soft limits for 'yumi_robr_joint_1': position [-2.91147; 2.91147], k: 1`
But defaults don't have to be bad, right?
What does seem bad is what follows half a second later:
`[ WARN] [1613153137.744638606]: Timed out while waiting for EGM feedback (did the EGM session end on the robot controller?)`

Anyway, I proceed with executing the other commands in different terminals. The `/yumi/egm/egm_states` topic indeed tells me that none of the channels are active:
```---
header: 
  seq: 777
  stamp: 
    secs: 1613154057
    nsecs: 739837082
  frame_id: ''
egm_channels: 
  - 
    name: "channel_1"
    active: False
    egm_convergence_met: False
    egm_client_state: 1
    motor_state: 1
    rapid_execution_state: 1
    utilization_rate: 0.0
  - 
    name: "channel_2"
    active: False
    egm_convergence_met: False
    egm_client_state: 1
    motor_state: 1
    rapid_execution_state: 1
    utilization_rate: 0.0
---
```

And a `rosservice call /yumi/rws/sm_addin/start_egm_joint "{}"` is not going to change that.
It does however go from `[Main]: Idling...` to `[EGM]: Waiting for fine point...` and then to `[EGM]: Starting joint motion` on both arms on the TeachPendant.

Starting the `ros_control` command controller with `rosservice call /yumi/egm/controller_manager/switch_controller` yields some more interesting error messages, but nothing else:

```
[ WARN] [1613153318.258354901]: Timed out while waiting for EGM feedback (did the EGM session end on the robot controller?)
[ WARN] [1613153327.885956360]: EGM is inactive! Refusing to start controller(s): [joint_group_velocity_controller]
[ERROR] [1613153327.886062625]: Could not switch controllers. The hardware interface combination for the requested controllers is unfeasible.
```

Any clue as to what is happening here, or how to resolve it?

**Comment by gavanderhoorn** [comment]
Could you please show us the exact command sequence (ie: `rosservice call`s) you use?

If you're performing some part of running programs manually (ie: by pressing the play button on the TP), please describe that instead, but keep the order in tact (ie: do not first list the `rosservice call`s, then the manual parts, but interleave them in the way you're actually performing actions).

As shows in the readmes, there is a specific order, and if you don't follow that order, things will not work.

**Comment by robberthofmanfm** [comment]
Of course. It's the exact same order that they're listed in [example 3](https://github.com/ros-industrial/abb_robot_driver/tree/master/abb_robot_bringup_examples#example-3-ex3_rws_and_egm_yumi_robot). At this point, I've tried many different orders, but I'll explicitize the one that I think I'm supposed to follow:
* I power on the YuMi and wait until the TeachPendant is booted up. It gives me an error about [absolute accuracy calibration](https://library.e.abb.com/public/5f8bca51d2b541709ea5d4ef165e46ab/3HAC052982%20PS%20IRB%2014000-en.pdf?x-sign=t3HHvF5H6qsxBC83e7PHCFA18NswGcGF9Y7f99vUKTWzvvzonYm8rlB5iHb9V6FP#d0e4044), which I then acknowledge. 
* Furthermore on the TeachPendant, I make sure the motors are on and the mode is auto. If the motors are not on, I switch to manual mode, put them on and then switch back to auto mode.
* I boot one computer that runs Windows and RobotStudio, and connect it to YuMi over WAN. This allows me to easily view the RAPID code of the state machine, follow the program pointer and set or view configuration.
* I boot another computer in Linux Ubuntu 20.04, which is connected directly to the YuMi service port and is set to assume the IP 192.168.125.50. 
* I go to the production window on the TeachPendant and click the physical play button. It now says 'running'. 
* On the Linux computer, after sourcing `devel/setup.zsh` in each terminal, I execute the following commands:
* `roslaunch abb_robot_bringup_examples ex3_rws_and_egm_yumi_robot.launch robot_ip:=192.168.125.1` that terminal gets filled with output and keeps running.
* I open another terminal and run `rostopic echo -c /yumi/egm/egm_states`. That too gets filled with output and keeps running.
* I open another terminal and execute `rosservice call /yumi/rws/stop_rapid "{}"`. I get a '1' result and see on the TeachPendant that the program has been stopped.
* In that same terminal, I execute `rosservice call /yumi/rws/pp_to_main "{}".` I get a '1' result.
* In that same terminal, I execute `rosservice call /yumi/rws/start_rapid "{}"`. I get a '1' result and see on the TeachPendant that the program has been started.
* In that same terminal, I execute `rosservice call /yumi/rws/sm_addin/start_egm_joint "{}"`. I get a '1' result and the TeachPendant prints out `[EGM]: Waiting for fine point...` and `[EGM]: Starting joint motion` for both arms.
* In that same terminal, I then execute ```rosservice call /yumi/egm/controller_manager/switch_controller "start_controllers: [joint_group_velocity_controller]
stop_controllers: ['']
strictness: 1
start_asap: false
timeout: 0.0"``` 
After executing this, the following appears in the first terminal:
```
[ WARN] [1613153327.885956360]: EGM is inactive! Refusing to start controller(s): [joint_group_velocity_controller]
[ERROR] [1613153327.886062625]: Could not switch controllers. The hardware interface combination for the requested controllers is unfeasible.
```
* I then open another terminal and execute `rostopic pub /yumi/egm/joint_group_velocity_controller/command std_msgs/Float64MultiArray "data: [0,0,0,0,0,0,-0.1,0,0,0,0,0,0,0.1]"`. It prints out `publishing and latching message. Press ctrl-C to terminate` and keeps running (never finishes). The YuMi does not move at all.

Hopefully that clarifies the process I'm following.

We do have an EGM license, but it is a colleague of mine who has installed this. Is there any way I can verify this?

**Comment by jontje** [comment]
Some follow-up questions and comments.

* YuMi side:
   * The EGM license can be checked via `RobotStudio > Controller tab > Configuration > Controller > Options` (if EGM is in the list, then it has been installed correctly).
   * Have you verified that the remote IP address specified for EGM communication is the same as your Ubuntu computer? Check via ` RobotStudio > Controller tab > Configuration > Communication > Transmission Protocol` (the StateMachine Add-In uses the `ROB_L` and `ROB_R` instances per default).
   * Where does the RAPID program pointer end up, for each arm, after you call the `start_egm_joint` ROS service? It should end up at `EGMRunJoint` instructions in the `TRobEGM` RAPID modules.

**Comment by robberthofmanfm** [comment]
Hey @jontje, thanks for the help.
EGM license is OK and robot indeed ends up at EGMRunJoint in the TRobEGM module after calling `start_egm_joint`.
The problem was indeed your second bullet point. 
Our communication configuration had 127.0.0.1 for the external computer, which is clearly wrong.

Our communication configuration is now as follows:
* ROB_L - UDPUC - 192.168.125.50 - 6511
* ROB_R - UDPUC - 192.168.125.50 - 6512

After restarting, we appear to be able to control the JointVelocities just fine, so many thanks for your help.

I also saw in the RAPID code that there is supposed to be a UCdevice or something. Is that the case? At what port should it run?
Should there be only those two (ROB_L/ROB_R) or are we missing more configurations? Should there be a TCP/IP device?

**Comment by gavanderhoorn** [comment]
If you can now control the robot, it would appear your configuration is correct.

There needn't necessarily be anything additional, unless you have a need for it.

**Comment by gavanderhoorn** [comment]
As the primary issue seems to have been resolved, I'm going to close this.

If there are any other/follow-up issues or questions @robberthofmanfm, please open a new issue.

**Comment by yanjunyangmonash** [comment]
Hi @robberthofmanfm

Would you mind provide me some help on connecting the virtual Ubuntu machine with the robotstudio without using the real robot? I met the same problem when running the yumi example.

I tried to
1. Set the static IP for the Ubuntu system using `sudo ifconfig ens33 192.168.125.50`
2. Test to ping the local Windows IP `ping 192.168.0.55`
3. Set the address of ROB_L and ROB_R following your recommendation

It worked well when testing the first example.

When I execute the command `rosservice call /yumi/rws/sm_addin/start_egm_joint "{}"`
The output gave the error `No data from the UdpUc device`

Do you have any idea about that?

**Comment by gavanderhoorn** [comment]
@yanjunyangmonash: could you please post a new issue instead? I'm sure @robberthofmanfm would be willing to comment on that too, but seeing as you're using RobotStudio, it would make for a nice separate documentation of that specific problem, instead of being 'burried' in the comments under another issue.

**Comment by yanjunyangmonash** [comment]
> @yanjunyangmonash: could you please post a new issue instead? I'm sure @robberthofmanfm would be willing to comment on that too, but seeing as you're using RobotStudio, it would make for a nice separate documentation of that specific problem, instead of being 'burried' in the comments under another issue.

Sorry, I already opened a new issue

**Comment by robberthofmanfm** [comment]
On the original topic again: since the issue was solved by configuring these two UDP ports in the network configuration, would it be possible to make that configuration part of the State-Machine Add-In?

**Comment by jontje** [comment]
> On the original topic again: since the issue was solved by configuring these two UDP ports in the network configuration, would it be possible to make that configuration part of the State-Machine Add-In?

FYI, these steps are already outlined in the StateMachine Add-In's [user manual](https://robotapps.blob.core.windows.net/appreferences/docs/cd504500-80e2-4cb6-9419-c60ea4ad6d56UserManual.pdf), under the "RobotStudio Simulation" section

**Comment by gavanderhoorn** [comment]
Note btw that the [Troubleshooting](https://github.com/ros-industrial/abb_robot_driver/tree/20d888d4891e62d3734c6be9d0ab759618a9e0c5/abb_egm_hardware_interface#troubleshooting) section in the readme of the `abb_egm_hardware_interface` package discusses some of the things reported by the OP here.
