### ISSUE TITLE
Cannot reproduce Example 3 only using the robotstudio+Ubuntu

### ISSUE THREAD

**Issue by yanjunyangmonash** [ros-industrial/abb_robot_driver#14]
I tried to build the connection between ROS and Robotstudio using a PC running Robotstudio and a virtual machine running Ubuntu18.04+ROS melodic

When I reproduced example 3, I met the same problem described in [https://github.com/ros-industrial/abb_robot_driver/issues/13](url)

Below are the commands sequence I used to run the example
1. I get the WindowsPC's IP address using `ipconfig`, but didn't make it static
2. Set the static IP for the Ubuntu system using `sudo ifconfig ens33 192.168.125.50`
3. Test to ping the local Windows IP `ping 192.168.0.55`
4. Set the address of ROB_L and ROB_R following @robberthofmanfm 's recommendation
5. In the robotstudiot -> controller -> configuration -> Transmission Protocol, I also set the address for UC device to `192.168.125.50`
6. Following the given sequence in example 3: `roslaunch abb_robot_bringup_examples ex3_rws_and_egm_yumi_robot.launch robot_ip:=192.168.0.55`

When I execute the command `rosservice call /yumi/rws/sm_addin/start_egm_joint "{}"`
The output gave the error `No data from the UdpUc device`.

Is there anyone could give me some hints or instructions?

**Comment by robberthofmanfm** [comment]
You should be able to ping the YuMi from your ubuntu virtual machine. If that's not the case, there's somthing wrong with your network setup.

At first sight, I believe the `robot_ip` you specified is not the IP address of the robot. 

You can find the YuMi IP address by looking in the menus on the TeachPendant.

A link that might help is the following:
[https://github.com/kth-ros-pkg/yumi/wiki/Network-setup](https://github.com/kth-ros-pkg/yumi/wiki/Network-setup)

**Comment by yanjunyangmonash** [comment]
Thanks for your reply. Do you mean the IP address shown here? But this cannot be connected
![image](https://user-images.githubusercontent.com/60594521/108863669-8f10dc80-7645-11eb-82df-1ea889e2c902.png)

**Comment by robberthofmanfm** [comment]
Yes that's what I mean. Why do you think it cannot be connected?

**Comment by yanjunyangmonash** [comment]
When I used ping `192.168.125.1`, I have this
![image](https://user-images.githubusercontent.com/60594521/108867163-04ca7780-7649-11eb-97c3-3f3a550d3d2a.png)

When I used this IP to launch the example, it gave the error
```
[ WARN] [1614094475.928211959]: Failed to establish RWS connection to the robot controller (attempt 1/5), reason: 'Failed to collect general system info'
[ WARN] [1614094475.930099608]: Failed to establish RWS connection to the robot controller (attempt 1/5), reason: 'Failed to collect general system info'
[ WARN] [1614094478.931692261]: Failed to establish RWS connection to the robot controller (attempt 2/5), reason: 'Failed to collect general system info'
[ WARN] [1614094478.934344559]: Failed to establish RWS connection to the robot controller (attempt 2/5), reason: 'Failed to collect general system info'
[ WARN] [1614094481.937202967]: Failed to establish RWS connection to the robot controller (attempt 3/5), reason: 'Failed to collect general system info'
[ WARN] [1614094481.938101305]: Failed to establish RWS connection to the robot controller (attempt 3/5), reason: 'Failed to collect general system info'
```

**Comment by robberthofmanfm** [comment]
You can always try to fiddle with your VM network settings by e.g. going to Devices > Network > Network settings and choose a Bridged Adapter instead of NAT.
I'm not an expert in VM networking so I don't know what the implications are of doing this, but it's another path that might result in a solution for you.

**Comment by yanjunyangmonash** [comment]
Hi @robberthofmanfm, you are correct. I changed the network settings and also did something else to make it work
1. Change the UbuntuPC IP address to make it has the same network segment as the Host IP
2. According to this [reply](https://github.com/ros-industrial/abb_libegm/issues/105#issuecomment-679849897), the IP address doesn't have to be 192.168.125.50
3. Add the client IP address to the white list based on this [answer](https://forums.robotstudio.com/discussion/12082/using-robotwebservices-to-access-a-remote-virtual-controller)
4. Modify the transmission protocol with the new client IP address
5. Test ping each other and run the launch command by using the new client IP address

**Comment by gavanderhoorn** [comment]
Seeing as you opened #15, I believe we can close this one.
