### ISSUE TITLE
Setup RobotStudio to work with the driver

### ISSUE THREAD

**Issue by DyumanAditya** [ros-industrial/abb_robot_driver#18]
Hi, 
I'm new to RobotStudio. How can I setup my workstation and controllers to be able to work with the driver? 
I want to be able to use the EGM feature.

I've followed [these old steps](http://wiki.ros.org/abb_driver/Tutorials/RobotStudio) up till "RobotStudio Setup". In addition to `616-1 PC interface` and `623-1 Multitasking` , I added `689-1 Externally Guided Motion`.  Is this the correct way to start?

**Comment by gavanderhoorn** [comment]
This is almost off-topic for this issue tracker.

For questions about RobotStudio, I'd refer you to the [RobotStudio fora](https://forums.robotstudio.com).

As to the required options for `abb_robot_driver`: that would indeed include EGM.

I don't believe the PC Interface is needed, as no data is received or transmitted from RAPID directly: RWS and EGM take care of that.

**Comment by gavanderhoorn** [comment]
As this not is an issue with the packages in this repository, I'm going to close it.

Please feel free to keep commenting on it of course.
