### ISSUE TITLE
use ros to connect and read images from the gripper camera

### ISSUE THREAD

**Issue by ruoshiwen** [ros-industrial/abb_robot_driver#31]
Hi,
I have a yumi with a gripper integrated with a camera. Does anyone know how to connect it with ros? Thanks a lot.

**Comment by gavanderhoorn** [comment]
I'm not aware of anything we support here unfortunately.

**Comment by gavanderhoorn** [comment]
I'm going to close the issue, as the packages in this repository are not YuMi specific, but a generic `ros_control` based EGM+RWS interface.

This may change in the future, but for now this is what it is.
