### ISSUE TITLE
Not possible to open the UdpUc device when running example 3

### ISSUE THREAD

**Issue by oruiz97** [ros-industrial/abb_robot_driver#32]
I am working with the abb_robot_driver in a Debian Buster machine running ROS Noetic and a Windows Virtualbox running RobotStudio. I installed the StateMachine Add-in when doing the controller setup. In the Transmission Protocol tab I changed the IP of the Remotre Adress of ROB_L, ROB_R and UCdevice to the Debian IP (following [this](https://github.com/ros-industrial/abb_libegm/issues/105#issuecomment-679849897). I have been trying to follow [Example 3](https://github.com/ros-industrial/abb_robot_driver/tree/master/abb_robot_bringup_examples#example-3-ex3_rws_and_egm_yumi_robot) as a starting point. 

When running the first command ([using the windows IP following this comment](https://github.com/ros-industrial/abb_libegm/issues/105#issuecomment-679854962))
`roslaunch abb_robot_bringup_examples ex3_rws_and_egm_yumi_robot.launch robot_ip:=<robot controller's IP address>
`

<details>
  <summary>The following messages show up </summary>

```log
 SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /yumi/egm/egm_state_controller/publish_rate: 250
 * /yumi/egm/egm_state_controller/type: abb_egm_state_con...
 * /yumi/egm/joint_group_velocity_controller/joints: ['yumi_robl_joint...
 * /yumi/egm/joint_group_velocity_controller/type: velocity_controll...
 * /yumi/egm/joint_state_controller/publish_rate: 250
 * /yumi/egm/joint_state_controller/type: joint_state_contr...
 * /yumi/egm_controller_stopper/no_service_timeout: False
 * /yumi/egm_controller_stopper/ros_control/controllers/always_ok_to_start: ['egm_state_contr...
 * /yumi/egm_controller_stopper/ros_control/controllers/ok_to_keep_running: ['egm_state_contr...
 * /yumi/egm_hardware_interface/egm/channel_1/mech_unit_group: rob_l
 * /yumi/egm_hardware_interface/egm/channel_1/port_number: 6511
 * /yumi/egm_hardware_interface/egm/channel_2/mech_unit_group: rob_r
 * /yumi/egm_hardware_interface/egm/channel_2/port_number: 6512
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_1/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_1/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_2/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_2/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_3/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_3/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_4/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_4/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_5/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_5/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_6/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_6/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_7/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robl_joint_7/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_1/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_1/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_2/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_2/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_3/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_3/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_4/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_4/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_5/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_5/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_6/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_6/max_velocity: 0.2
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_7/has_velocity_limits: True
 * /yumi/egm_hardware_interface/joint_limits/yumi_robr_joint_7/max_velocity: 0.2
 * /yumi/egm_hardware_interface/no_service_timeout: False
 * /yumi/egm_hardware_interface/ros_control/controllers/always_ok_to_start: ['egm_state_contr...
 * /yumi/egm_hardware_interface/ros_control/controllers/ok_to_keep_running: ['egm_state_contr...
 * /yumi/rws_service_provider/no_connection_timeout: False
 * /yumi/rws_service_provider/robot_ip: 147.83.37.126
 * /yumi/rws_service_provider/robot_nickname: yumi
 * /yumi/rws_service_provider/robot_port: 80
 * /yumi/rws_state_publisher/no_connection_timeout: False
 * /yumi/rws_state_publisher/polling_rate: 5
 * /yumi/rws_state_publisher/robot_ip: 147.83.37.126
 * /yumi/rws_state_publisher/robot_nickname: yumi
 * /yumi/rws_state_publisher/robot_port: 80

NODES
  /yumi/
    egm_controller_stopper (abb_egm_hardware_interface/egm_controller_stopper)
    egm_hardware_interface (abb_egm_hardware_interface/egm_hardware_interface)
    rws_service_provider (abb_rws_service_provider/rws_service_provider)
    rws_state_publisher (abb_rws_state_publisher/rws_state_publisher)
  /yumi/egm/
    started (controller_manager/spawner)
    stopped (controller_manager/spawner)

auto-starting new master
process[master]: started with pid [14413]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7e62c26a-16d4-11ec-9a0b-305a3a7a90fb
process[rosout-1]: started with pid [14433]
started core service [/rosout]
process[yumi/rws_state_publisher-2]: started with pid [14436]
process[yumi/rws_service_provider-3]: started with pid [14437]
process[yumi/egm_hardware_interface-4]: started with pid [14438]
process[yumi/egm_controller_stopper-5]: started with pid [14439]
process[yumi/egm/started-6]: started with pid [14440]
process[yumi/egm/stopped-7]: started with pid [14441]
[ WARN] [1631786247.115013076]: Configured default soft limits for 'yumi_robr_joint_1': position [-2.91147; 2.91147], k: 1
[ WARN] [1631786247.117384750]: Configured default soft limits for 'yumi_robr_joint_2': position [-2.4795; 0.751626], k: 1
[ WARN] [1631786247.119752635]: Configured default soft limits for 'yumi_robr_joint_3': position [-2.91147; 2.91147], k: 1
[ WARN] [1631786247.121864998]: Configured default soft limits for 'yumi_robr_joint_4': position [-2.13393; 1.3823], k: 1
[ WARN] [1631786247.123981950]: Configured default soft limits for 'yumi_robr_joint_5': position [-5.01084; 5.01084], k: 1
[ WARN] [1631786247.125665528]: Configured default soft limits for 'yumi_robr_joint_6': position [-1.52053; 2.38446], k: 1
[ WARN] [1631786247.127468186]: Configured default soft limits for 'yumi_robr_joint_7': position [-3.95683; 3.95683], k: 1
[ WARN] [1631786247.129118829]: Configured default soft limits for 'yumi_robl_joint_1': position [-2.91147; 2.91147], k: 1
[ WARN] [1631786247.130769508]: Configured default soft limits for 'yumi_robl_joint_2': position [-2.4795; 0.751626], k: 1
[ WARN] [1631786247.132446905]: Configured default soft limits for 'yumi_robl_joint_3': position [-2.91147; 2.91147], k: 1
[ WARN] [1631786247.134145853]: Configured default soft limits for 'yumi_robl_joint_4': position [-2.13393; 1.3823], k: 1
[ WARN] [1631786247.135747252]: Configured default soft limits for 'yumi_robl_joint_5': position [-5.01084; 5.01084], k: 1
[ WARN] [1631786247.137314808]: Configured default soft limits for 'yumi_robl_joint_6': position [-1.52053; 2.38446], k: 1
[ WARN] [1631786247.138874728]: Configured default soft limits for 'yumi_robl_joint_7': position [-3.95683; 3.95683], k: 1
[ WARN] [1631786247.573903890]: Timed out while waiting for EGM feedback (did the EGM session end on the robot controller?)
[ WARN] [1631786257.593511915]: Timed out while waiting for EGM feedback (did the EGM session end on the robot controller?)
[ WARN] [1631786267.612823047]: Timed out while waiting for EGM feedback (did the EGM session end on the robot controller?)
[ WARN] [1631786277.632128734]: Timed out while waiting for EGM feedback (did the EGM session end on the robot controller?)
[ WARN] [1631786287.651184794]: Timed out while waiting for EGM feedback (did the EGM session end on the robot controller?)
```

</details>

The `[ WARN] [1631786247.573903890]: Timed out while waiting for EGM feedback (did the EGM session end on the robot controller?)` keeps going, which [I think is to be expected](https://github.com/ros-industrial/abb_robot_driver/issues/20#issuecomment-796615332)

I start the StateMachine loop and the virtual Flexpendant shows the `Idling... `message. At this stage I have checked that I have basic communication with Robotstudio. For instance, running `rosservice call yumi/rws/set_motors_off` results in a Motors OFF message in Robotstudio and `rostopic echo /yumi/rws/joint_states `gives me the current joint values. 

Following the example, I run in another terminal `rostopic echo -c /yumi/egm/egm_states`

```yaml
header: 
  seq: 14877
  stamp: 
    secs: 1631787735
    nsecs: 698707841
  frame_id: ''
egm_channels: 
  - 
    name: "channel_1"
    active: False
    egm_convergence_met: False
    egm_client_state: 1
    motor_state: 1
    rapid_execution_state: 1
    utilization_rate: 0.0
  - 
    name: "channel_2"
    active: False
    egm_convergence_met: False
    egm_client_state: 1
    motor_state: 1
    rapid_execution_state: 1
    utilization_rate: 0.0
---
```

The trouble comes when I try to start the EGM session doing `rosservice call /yumi/rws/sm_addin/start_egm_joint "{}"
`. On the ROS side I get 

`result_code: 1
message: ''
`

While in RobotStudio I get an Execution Error which pauses the T_Rob tasks

```
41824: Not possible to open the UdpUc device
Description
It was not possible to open the external device ROB_L that was specified in the RAPID instruction EGMSetupUC.
Consequences
The program execution is stopped immediately.
Actions
Check if:
1. The device name is spelled correctly.
2. The device is connected.
3. The device is up and running.
```

It may be worth mentioning that I have also tried to follow the steps in the State Machine Add-in manual, in the [Simulation section](https://robotapps.blob.core.windows.net/appreferences/docs/cd504500-80e2-4cb6-9419-c60ea4ad6d56UserManual.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C61%2C427%2C0%5D), and the same error appears when I manually set the EGM_START_JOINT signal to 1 in the I/O Simulator.

I would appreciate any help to eliminate this error and be able to start the EGM session.

**Comment by gavanderhoorn** [comment]
> I am working with the abb_robot_driver in a Debian Buster machine running ROS Noetic and a Windows Virtualbox running RobotStudio

what sort of networking is the VM using?

A NATted NIC could be problematic. You'll need full bi-directional traffic between the VM guest and your "ROS IP" (by which I mean: whichever interface you are binding the node to).

You'll also want to make sure the Windows firewall is not interfering.

For now this doesn't appear to be a problem with the driver, but more a general network setup issue.

**Comment by oruiz97** [comment]
I'm using Bridged Networking between my VM and Debian. The promiscuous mode setting has been set to "allow everything". I had seen other issues mentioning issues with the Windows firewall so I had already turned it off. The same issue still persists

**Comment by gavanderhoorn** [comment]
Ports are configured correctly as well (https://github.com/ros-industrial/abb_libegm/issues/105#issuecomment-681168149)?

**Comment by gavanderhoorn** [comment]
And #14 contains some experiences of other users as well.

**Comment by oruiz97** [comment]
Ports have been setup like this. Remote address is the ROS IP.
![ports](https://user-images.githubusercontent.com/90834957/134135599-6da23d0e-5f20-4d8f-9753-850945ba07ac.png)
:
I also followed the steps in https://github.com/ros-industrial/abb_robot_driver/issues/14#issuecomment-785127331

**Comment by gavanderhoorn** [comment]
I don't believe all ports should be identical. That can't really work, as `ROB_L` and `ROB_R` need different data:

https://github.com/ros-industrial/abb_robot_driver/blob/32eb0f48abfd3358cb5a4f3f043f1306a9811b24/abb_robot_bringup_examples/config/ex3_hardware_egm.yaml#L1-L10

**Comment by oruiz97** [comment]
I finally managed to get my hands on our Yumi and running the example 3 on real hardware works properly. The issue with the simulation on RobotStudio remains. We have been having some trouble with the RobotStudio licenses so it may be related to that.

**Comment by jontje** [comment]
@oruiz97, great that it works with the real robot.

> The issue with the simulation on RobotStudio remains. We have been having some trouble with the RobotStudio licenses so it may be related to that.

If possible, could you post which type of license you have for RobotStudio? It should be shown in the `About RobotStudio` section found at `RobotStudio > File tab > Help`. I.e. it should look something like this:

![About RobotStudio](https://user-images.githubusercontent.com/16589371/135235818-86564eda-5d6a-4a53-b862-ab09b20389a3.png)

**Comment by oruiz97** [comment]
@jontje We fixed our license issue and now I seem to be able to do everything I have been doing with the real Yumi in Robotstudio. For reference, this is the license information we have now, I don't have a snapshot of what we had before. It appears to be that this was the cause of the issue, as it's the only change I made in between that I can recall.

![imatge](https://user-images.githubusercontent.com/90834957/135411740-b72a9ecb-6509-461f-ba7f-ac2cb6ef2f9d.png)

**Comment by oruiz97** [comment]
Apologies if this isn't the right place to ask, but while the robot control part works in robotstudio, when trying to open and close the gripper the following message shows up in the virtual Flexpendant

`Virtual controller (gripper is not simulated)`

I'm using the same services that let me open and close the gripper in the real Yumi

**Comment by gavanderhoorn** [comment]
Please do not post follow-up questions under already resolved issues.

If appropriate, open a new issue.

It doesn't seem like this is an issue with the packages in this driver though.

**Comment by jontje** [comment]
> Apologies if this isn't the right place to ask, but while the robot control part works in robotstudio, when trying to open and close the gripper the following message shows up in the virtual Flexpendant
> 
> `Virtual controller (gripper is not simulated)`

Yes, that is because the virtual controller (i.e. background process running RobotWare and RAPID code) doesn't simulate SmartGrippers as far as I know, which is a separate system.

Additionally, I second @gavanderhoorn option about opening new issues if appropriate.
