### ISSUE TITLE
Failed to establish RWS connection to the robot controller

### ISSUE THREAD

**Issue by zhangzhihao2020** [ros-industrial/abb_robot_driver#34]
When I use RobotStudio virtual environment to test Example 2: "ex2_rws_and_egm_6axis_robot", the following error occurred:
```
[ WARN] [1632303078.269721921]: Failed to establish RWS connection to the robot controller (attempt 5/5), reason: 'Failed to collect general system info'
[FATAL] [1632303079.273911410]: Runtime error: 'Failed to establish RWS connection to the robot controller'
[FATAL] [1632303079.274646500]: Runtime error: 'Failed to establish RWS connection to the robot controller'
[rws_state_publisher-1] process has died [pid 18381, exit code 1, cmd /home/zzh/catkin_ws6/devel/lib/abb_rws_state_publisher/rws_state_publisher __name:=rws_state_publisher __log:=/home/zzh/.ros/log/9005a602-1b86-11ec-8087-484d7ee72552/rws_state_publisher-1.log].
log file: /home/zzh/.ros/log/9005a602-1b86-11ec-8087-484d7ee72552/rws_state_publisher-1*.log
[rws_service_provider-2] process has died [pid 18382, exit code 1, cmd /home/zzh/catkin_ws6/devel/lib/abb_rws_service_provider/rws_service_provider __name:=rws_service_provider __log:=/home/zzh/.ros/log/9005a602-1b86-11ec-8087-484d7ee72552/rws_service_provider-2.log].
log file: /home/zzh/.ros/log/9005a602-1b86-11ec-8087-484d7ee72552/rws_service_provider-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```
Does anyone know how to solve it, thanks !

**Comment by gavanderhoorn** [comment]
There could be many causes here.

Incorrect IPs, firewall on the Windows side, firewall on the Linux side, you haven't whitelisted the IP address of the Linux side for access to RWS in RobotStudio (see https://github.com/ros-industrial/abb_librws/issues/81), etc, etc.

Without more information it's going to be difficult to help you.

Please also review [closed issues](https://github.com/ros-industrial/abb_robot_driver/issues?q=is%3Aissue+is%3Aclosed), as some may already deal with your problem.

**Comment by gavanderhoorn** [comment]
As for now I believe this is a configuration issue rather than a problem with the packages in this repository, I'm going to close the issue.

If it turns out something does in fact need to be fixed here, we can re-open.

Feel free to keep commenting on your issue of course.

**Comment by jontje** [comment]
@zhangzhihao2020, if the RWS communication issue still persists, then it might be useful to, for example, take a look at the [troubleshooting](https://github.com/ros-industrial/abb_robot_driver/blob/master/abb_rws_state_publisher/README.md#troubleshooting) section for `abb_rws_state_publisher`.

**Comment by Levelsss** [comment]
Same mistake, my situation is different. Without making any changes, I just left my computer for a while and then re-ran the program and there was an error:
```
Failed to establish RWS connection to the robot controller
```
Restart the computer, the error disappeared, very strange.
