### ISSUE TITLE
Commands out of range from previous executions block the robot

### ISSUE THREAD

**Issue by oruiz97** [ros-industrial/abb_robot_driver#35]
I have been successfully using the driver to send trajectories to a Yumi using a joint trajectory controller. However during some testing I made a mistake and started sending out of range trajectories to the left arm. I received an` External Motion Interface input out of bounds `error message, which was to be expected. However, ever since then every time I start a new egm joint session the same error appears, closing motors and stopping execution. Here's the actions I took to try to fix the problem:
- Restarting both the PC and Yumi
- Using a backup for the robot controller that's a few weeks old
- Checked that the RWS services work, the error only appears after running the `rosservice call /rws/sm_addin/start_egm_joint "{}"` command
- I have tested to turn off the T_ROB_L task and move the right arm with the code I had before (not the test that had the mistakes, a previously done and tested version), and it works as intended. So the problem is localized on starting an egm joint session on the left arm
- Went back and used [example 3](https://github.com/ros-industrial/abb_robot_driver/tree/master/abb_robot_bringup_examples#example-3-ex3_rws_and_egm_yumi_robot) of `abb_robot_bringup_examples` in case it was an issue with my implementation, but the problem remains (if T_ROB_L is turned off the example also works as intended)

On the ROS side, the error that appears is:

```
[FATAL] [1636457172.405139789]: Out of range: 'Joint command is out-of-bounds'
[yumi/egm_hardware_interface-12] process has died [pid 11294, exit code 1, cmd /home/users/user.name/catkin_ws2/devel/lib/abb_egm_hardware_interface/egm_hardware_interface __name:=egm_hardware_interface __log:=/home/users/user.name/.ros/log/ca8338b4-414f-11ec-b1b1-305a3a7a90fb/yumi-egm_hardware_interface-12.log].
log file: /home/users/user.name/.ros/log/ca8338b4-414f-11ec-b1b1-305a3a7a90fb/yumi-egm_hardware_interface-12*.log

```

My best guess is that the out of bounds joint commands have been stored somewhere and everytime I start an egm joint on the left arm the robot tries to perform them, but I would appreciate help in order to fix it.

**Comment by gavanderhoorn** [comment]
Hm, interesting.

I don't have any immediate ideas. Perhaps @jontje has some insight he could share.

**Comment by oruiz97** [comment]
Another test I have tried just now is using the flex pendant to manually set the EGM_START_JOINT to 1. When I do that, I see the corresponding `Starting joint motion message` on the pendant's screen. But then when I try to launch example 3 the same error appears, this time without needing to call the `/rws/sm_addin/start_egm_joint ` service. I take this to mean that the issue doesn't lie in the robot, as the error only appears when communication with the PC is activated

**Comment by gavanderhoorn** [comment]
Glad to hear you got it to work again.

Thanks for reporting back.
