### ISSUE TITLE
set_rapid_symbol service usage

### ISSUE THREAD

**Issue by bhomaidan1990** [ros-industrial/abb_robot_driver#38]
Hi, 
I'm trying to use the srevice `/yumi/rws/set_rapid_symbol` defined [here](https://github.com/ros-industrial/abb_robot_driver_interfaces/blob/master/abb_robot_msgs/srv/SetRAPIDSymbol.srv) and I'm using this code:
```py
import rospy
from abb_rapid_msgs.msg import *
from abb_robot_msgs.srv import *
from abb_robot_msgs.msg import *
from abb_rapid_sm_addin_msgs.srv import *

def set_RAPID_symbol( symbol_name, symbol_val, module='TRobRapid', left=True):
        """
        Function: set_RAPID_symbol, to set symbols inside RAPID using StateMachine Add-In.
        ---
        Parameters
        @param symbol_name: str, the name of the symbol in RAPID.
        @param symbol_val: str, the value of the symbol as plain text.
        @param module_: str, the RAPID script that includes the symbol.
        @param left: bool, select left arm, True for Left, False for Right arm selection.
        ---
        return None
        """
        rospy.wait_for_service('/yumi/rws/set_rapid_symbol')
        set_symbol  = rospy.ServiceProxy('/yumi/rws/set_rapid_symbol', SetRAPIDSymbol)

        # Task
        task_L = 'T_ROB_L'
        task_R = 'T_ROB_R'
        if left:
            task_ = task_L
        else:
            task_ = task_R

        # RAPID Symbol Path message
        symbol_path_ = RAPIDSymbolPath()
        symbol_path_.task = task_
        symbol_path_.module = module
        symbol_path_.symbol = symbol_name
        # Set RAPID Symbol
        set_symbol(symbol_path_, symbol_val)
```
I'm calling the service as in the function, and get:
```
result_code: 2
message: "\"Service failed (e.g. timeout or resource not found, see the DEBUG log for details)\""
```
What I'm trying to do is to change the speed symbol `VAR speeddata pp_speed := v100` and the pick/place positions `VAR robtarget pickoint; VAR robtarget placepoint;` dynamically using ROS interface, I have defined these variables in `TRobRAPID` module in `T_ROB_L` task but sadly I wasn't able to change the values of some of these symbols, and whenever I call the `/yumi/rws/sm_addin/run_rapid_routine` service, the variable has the predefined value that didn't change! can you please tell me how can I use this service correctly? thanks in advance.

---

## Update:
I was able to set the speed by setting the value to `[200,500,5000,1000]` as string, instead of `v200` by inspecting the value coming from the same `symbol_path_` and modifying it later.
But the same approach **didn't work for some variables such as `robtarget` variable!** I'm even reading the same symbol value and trying to assign it as it is again, but it didn't work, can you please explain to me why this approach worked for one variable (`speeddata`), and didn't work for the other(`robtarget`)? thanks in advance.
```py
get_symbol  = rospy.ServiceProxy('/yumi/rws/get_rapid_symbol', GetRAPIDSymbol)
# symbol_path as the code above
response = get_symbol(symbol_path_)
print('\n {} response\n'.format(symbol_name), response.value)
print('\n', symbol_name, symbol_val, '\n')
exam = set_symbol(symbol_path_, response.value)
print('\n {} exam \n'.format(symbol_name), exam)
```
Output:
```
 pp_speed response
 [200,500,5000,1000]

 pp_speed [200,500,5000,1000] 


 pp_speed exam 
 result_code: 1
message: ''

 pickpoint response
 [[490.311,354.868,159.45],[0.00844173,0.99991,-0.00255942,0.0101336],[-1,-1,0,5],[-144.112,9E+09,9E+09,9E+09,9E+09,9E+09]]

 pickpoint [[233.4869,385.8356,106.2663],[0.009619514,0.9998696,0.002840401,0.0126574],[-1,1,2,4],[171.2644,9E+09,9E+09,9E+09,9E+09,9E+09]] 


 pickpoint exam 
 result_code: 2
message: "\"Service failed (e.g. timeout or resource not found, see the DEBUG log for details)\""

 placepoint response
 [[412.041,33.0727,158],[0.000151984,-0.999942,0.009992,-0.00394568],[-1,2,1,4],[168.762,9E+09,9E+09,9E+09,9E+09,9E+09]]

 placepoint [[395.148,1.740897,107.2843],[0.00729238,0.7069148,0.7071888,0.01011433],[-1,1,1,4],[-146.7749,9E+09,9E+09,9E+09,9E+09,9E+09]] 


 placepoint exam 
 result_code: 2
message: "\"Service failed (e.g. timeout or resource not found, see the DEBUG log for details)\""
```

**Comment by gavanderhoorn** [comment]
As the last line of your console copy-paste suggests, I would recommend to increase the logger level to `DEBUG` and see what [this line](https://github.com/ros-industrial/abb_robot_driver/blob/72c71f7d85e4896e34b5cd8ec68c73c409756006/abb_rws_service_provider/src/rws_service_provider_core_srvs.cpp#L597) reports.

**Comment by bhomaidan1990** [comment]
The solution was to change `9E+09,9E+09,9E+09,9E+09,9E+09` to `9E9,9E9,9E9,9E9,9E9`, and everything went fine then.

**Comment by bhomaidan1990** [comment]
The solution was to change `9E+09,9E+09,9E+09,9E+09,9E+09` to `9E9,9E9,9E9,9E9,9E9`, and everything went fine then.
